#ifndef _YUSUR_ROCE_DEVICE_H
#define _YUSUR_ROCE_DEVICE_H

enum yusur_roce_reset_stage {
	YUSUR_ROCE_STATE_NON_RST,
	YUSUR_ROCE_STATE_RST_BEF_DOWN,
	YUSUR_ROCE_STATE_RST_DOWN,
	YUSUR_ROCE_STATE_RST_UNINIT,
	YUSUR_ROCE_STATE_RST_INIT,
	YUSUR_ROCE_STATE_RST_INITED,
};

enum yusur_roce_instance_state {
	YUSUR_ROCE_STATE_NON_INIT,
	YUSUR_ROCE_STATE_INIT,
	YUSUR_ROCE_STATE_INITED,
	YUSUR_ROCE_STATE_UNINIT,
};

#endif /* _YUSUR_ROCE_DEVICE_H */